import { chromium } from 'playwright';
const out = process.argv[2] || '/tmp/gun_test.png';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.setViewportSize({ width: 1280, height: 720 });
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' });
await page.waitForTimeout(4500);
await page.screenshot({ path: out });
await browser.close();
console.log('saved:', out);
