// © 2026 lizard.build — https://lizard.build — All rights reserved. See LICENSE.
// Ported from escape-tsuami-client/src/game/map/worker/types.ts, BType trimmed
// down to the blocks this project actually uses.

export enum BType {
  air = 0,
  grass = 1,
  dirt = 2,
  stone = 3,
  sand = 4,
  snow = 5,
  log = 6,
  leaf = 7,
  planks = 8,
  water = 9,
  coal_ore     = 10,
  iron_ore     = 11,
  gold_ore     = 12,
  diamond_ore  = 13,
  emerald_ore  = 14,
  lapis_ore    = 15,
  redstone_ore = 16,
  cherry_log   = 17,
  cherry_leaf  = 18,
  // World import block types
  smooth_sandstone    = 19,
  white_concrete      = 20,
  smooth_red_sandstone = 21,
  smooth_stone        = 22,
  light_gray_concrete = 23,
  yellow_terracotta   = 24,
  stone_bricks        = 25,
  coal_block          = 26,
  prismarine_bricks   = 27,
  white_terracotta    = 28,
  cyan_terracotta     = 29,
  red_terracotta      = 30,
  green_terracotta    = 31,
  lime_terracotta     = 32,
  cobblestone         = 33,
  sandstone           = 34,
  bricks              = 35,
  chest               = 36,
  chain               = 37,
  // Half-height slab types (rendered by SlabLayer)
  cut_sandstone_slab       = 38,
  smooth_sandstone_slab    = 39,
  smooth_stone_slab        = 40,
  smooth_red_sandstone_slab = 41,
  oak_slab                 = 42,
  stone_brick_slab         = 43,
  prismarine_brick_slab    = 44,
  // Thin/cross-post block types (rendered by CrossPostLayer)
  iron_bars                = 45,
  glass_pane               = 46,
  oak_fence                = 47,
  // Door types (rendered by DoorLayer)
  oak_door                 = 48,
  // Trapdoor types — full state encoded in BType:
  // BType = trapdoor_base + type*16 + open*8 + facing*2 + half
  // type: 0=oak, 1=iron, 2=mangrove, 3=spruce
  // open: 0=closed(flat horizontal), 1=open(vertical wall panel)
  // facing: 0=north, 1=south, 2=east, 3=west
  // half: 0=bottom, 1=top
  oak_trapdoor             = 49,  // keep for legacy fallback (not generated by new converter)
  trapdoor_base            = 114, // IDs 114–177
  // Top-half slab types (178-184) — same order as bottom slabs (38-44)
  // top_slab_id = bottom_slab_id + 140
  cut_sandstone_slab_top       = 178,
  smooth_sandstone_slab_top    = 179,
  smooth_stone_slab_top        = 180,
  smooth_red_sandstone_slab_top = 181,
  oak_slab_top                 = 182,
  stone_brick_slab_top         = 183,
  prismarine_brick_slab_top    = 184,
  // Stair block types — orientation encoded as (id - base) = facing*2+half
  // facing: north=0,south=1,east=2,west=3  half: bottom=0,top=1
  stone_brick_stairs          = 50,  // IDs 50-57
  smooth_sandstone_stairs     = 58,  // IDs 58-65
  sandstone_stairs            = 66,  // IDs 66-73
  smooth_red_sandstone_stairs = 74,  // IDs 74-81
  oak_stairs                  = 82,  // IDs 82-89
  prismarine_brick_stairs     = 90,  // IDs 90-97
  cobblestone_stairs          = 98,  // IDs 98-105
  brick_stairs                = 106, // IDs 106-113
  // Door block types — facing encoded as (id - door_base): N=0, S=1, E=2, W=3
  // Both upper and lower halves of a door share the same facing ID.
  door_base                   = 185, // IDs 185-188
}

export interface Pos3 {
  x: number;
  y: number;
  z: number;
}

export interface Pos2 {
  x: number;
  z: number;
}

export interface Palette {
  default: Record<number, number>;
  reversed: Partial<Record<number, number>>;
  cnt: number;
}
